######################################################################
# Automatically generated by qmake (2.01a) czw. wrz 29 21:29:52 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window_qt.hpp
SOURCES += main.cpp window_qt.cpp
