######################################################################
# Automatically generated by qmake (2.01a) czw. pa? 20 12:36:44 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window_qt.hpp
SOURCES += main.cpp window_qt.cpp
